// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	message: "Hello World"
	image: {
		repository: "nginx"
		tag:        "1.29.3"
		digest:     "sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42"
	}


	// test: image: {
	// 	repository: "cgr.dev/chainguard/curl"
	// 	digest:     ""
	// 	tag:        "latest"
	// }
}
